[package]
name = "calc-api"
version.workspace = true
edition.workspace = true

[dependencies]
common = { path = "../common" }
rocket = { version = "0.5.0", features = ["json"] }
serde_json.workspace = true