[package]
name = "calc-ui"
version.workspace = true

[dependencies]
yew = { git = "https://github.com/yewstack/yew/", features = ["csr"] }
common = { path = "../common" }
wasm-logger = "0.2.0"
log.workspace = true
serde.workspace = true
serde_json.workspace = true