[package]
name = "api"
version.workspace = true
edition.workspace = true

[dependencies]
shared = { path = "../shared" }
serde.workspace = true
serde_json.workspace = true
rocket = { version = "0.5.0", features = ["json"] }