name: Cargo Build & Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Build web release
      run: |
        cargo install --locked trunk
        trunk build --release
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_REGISTRY_TOKEN }}
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      with:
        directory: web
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.ref }}
          ghcr.io/${{ github.repository }}:latest